// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-WUJDKZjidmJm_EF3NI0hIUKmW5hBkc',
    appId: '1:530725892434:web:1719e2e5ec4c742431ca8b',
    messagingSenderId: '530725892434',
    projectId: 'score-board-eca1e',
    authDomain: 'score-board-eca1e.firebaseapp.com',
    databaseURL: 'https://score-board-eca1e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'score-board-eca1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtTUbglMCFhPswStp9xL_XwmVwrzCaOu4',
    appId: '1:530725892434:android:5d29c5dd201b597231ca8b',
    messagingSenderId: '530725892434',
    projectId: 'score-board-eca1e',
    databaseURL: 'https://score-board-eca1e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'score-board-eca1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRx-ZDTqWPG_P9vQFY_kB6ywo9ZyXXbAE',
    appId: '1:530725892434:ios:501091343909e1ca31ca8b',
    messagingSenderId: '530725892434',
    projectId: 'score-board-eca1e',
    databaseURL: 'https://score-board-eca1e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'score-board-eca1e.appspot.com',
    iosClientId: '530725892434-ph2e4ao8rulrhj1km2bspc73ennfqgi9.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoreBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRx-ZDTqWPG_P9vQFY_kB6ywo9ZyXXbAE',
    appId: '1:530725892434:ios:501091343909e1ca31ca8b',
    messagingSenderId: '530725892434',
    projectId: 'score-board-eca1e',
    databaseURL: 'https://score-board-eca1e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'score-board-eca1e.appspot.com',
    iosClientId: '530725892434-ph2e4ao8rulrhj1km2bspc73ennfqgi9.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoreBoard',
  );
}
